### ISSUE TITLE
Will mongodb transport be released?

### ISSUE THREAD

**Issue by alandecastros** [rebus-org/Rebus.MongoDb#17]
Any release date for mongodb transport?

**Comment by mookid8000** [comment]
Rebus.MongoDb 8.0.0-alpha02 (which is on NuGet.org now) has a MongoDB-based transport 🙂 

It's based on https://github.com/rebus-org/MongolianBarbecue , so while the Rebus integration should be considered experimental, the transport itself (i.e. the MongoDB operations associated with making it behave like a queueing system) is fairly well-tested.
