### ISSUE TITLE
Issue with index creation

### ISSUE THREAD

**Issue by alandecastros** [rebus-org/Rebus.MongoDb#18]
In my company I don't have permissiton to create an index. Can we make it optional?

**Comment by mookid8000** [comment]
It was already possible to disable for the MongoDB saga storage, but I also made it possible when using MongoDB as the transport.

You can see how it's done here: https://github.com/rebus-org/Rebus.MongoDb/blob/master/Rebus.MongoDb.Tests/Examples/DoNotCreateIndexes.cs

It's available in Rebus.MongoDb 8.0.0-alpha03 which is on NuGet.org now 🙂
