### ISSUE TITLE
Any plans to upgrade to MongoDb.Driver 2.7.3?

### ISSUE THREAD

**Issue by Efp95** [rebus-org/Rebus.MongoDb#2]
Just wondering! 😄 
https://github.com/mongodb/mongo-csharp-driver

**Comment by mookid8000** [comment]
well... although the dependency on version 2.4.4 causes that version to be resolved when you install Rebus.MongoDb, you can still upgrade the mongo driver afterwards by explicitly installing a newer version
```psh
install-package mongocsharpdriver -projectname <your-project>
```
which will cause Rebus.MongoDb to use that version instead.

Is there any specific reason why you think an upgrade from 2.4.4 to 2.7.3 (which is current, at the time of writing) would be beneficial?
