### ISSUE TITLE
MongoDb Transport

### ISSUE THREAD

**Issue by StylesLab** [rebus-org/Rebus.MongoDb#9]
Does Rebus.MongoDb support MongoDB for Transport? Or only storage Subscriptions and Sagas?

If no, should I implement my own (https://github.com/rebus-org/Rebus/issues/840) or are there very good reasons not to?

**Comment by mookid8000** [comment]
Rebus does not have a MongoDB transport 🙂 but funnily enough I actually made [MongolianBarbecue](https://github.com/rebus-org/MongolianBarbecue), which is a MongoDB-based queue implementation, which should be fairly easy to adapt or bake into a Rebus-capable transport implementation...
